from django.urls import path

from .views import (
    about_page,
    article_list,
    contact_page,
    add_gallery_comment,
    add_article_comment,
    create_trend_article,
    create_gallery_post,
    delete_gallery_comment,
    delete_article_comment,
    delete_trend_article,
    delete_gallery_post,
    delete_notification,
    full_article_page,
    list_notifications,
    gallery_page,
    insights_page,
    mark_notification_read,
    profile_view,
    save_profile_color,
    signup_view,
    style_lens_analyze,
    style_lens_page,
    toggle_gallery_heart,
    trend_article_detail,
    trends_page,
    user_gallery_page,
    verify_email,
)

urlpatterns = [
    path('', article_list, name='home'),
    path('gallery/', gallery_page, name='gallery'),
    path('gallery/new/', create_gallery_post, name='gallery-create'),
    path('gallery/user/<str:username>/', user_gallery_page, name='user-gallery'),
    path('gallery/<int:post_id>/heart/', toggle_gallery_heart, name='gallery-heart'),
    path('gallery/<int:post_id>/comment/', add_gallery_comment, name='gallery-comment'),
    path('gallery/comment/<int:comment_id>/delete/', delete_gallery_comment, name='gallery-comment-delete'),
    path('gallery/<int:post_id>/delete/', delete_gallery_post, name='gallery-delete'),
    path('trends/', trends_page, name='trends'),
    path('trends/new/', create_trend_article, name='trend-create'),
    path('trends/<slug:slug>/delete/', delete_trend_article, name='trend-delete'),
    path('trends/<slug:slug>/comment/', add_article_comment, name='article-comment-add'),
    path('trends/comment/<int:comment_id>/delete/', delete_article_comment, name='article-comment-delete'),
    path('trends/<slug:slug>/', trend_article_detail, name='trend-article-detail'),
    path('article/minimalist-power-dressing/', full_article_page, name='article-detail'),
    path('insights/', insights_page, name='insights'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('signup/', signup_view, name='signup'),
    path('verify/', verify_email, name='verify-email'),
    path('profile/', profile_view, name='profile'),
    path('profile/color/', save_profile_color, name='save-profile-color'),
    path('notifications/', list_notifications, name='notification-list'),
    path('notifications/<int:notification_id>/read/', mark_notification_read, name='notification-read'),
    path('notifications/<int:notification_id>/delete/', delete_notification, name='notification-delete'),
    path('style-lens/', style_lens_page, name='style-lens'),
    path('style-lens/analyze/', style_lens_analyze, name='style-lens-analyze'),
]
