from django.urls import path

from .views import (
    about_page,
    article_list,
    contact_page,
    add_gallery_comment,
    add_article_comment,
    create_trend_article,
    create_gallery_post,
    delete_gallery_comment,
    delete_article_comment,
    delete_gallery_post,
    full_article_page,
    insights_page,
    profile_view,
    signup_view,
    toggle_gallery_heart,
    trend_article_detail,
    trends_page,
)

urlpatterns = [
    path('', article_list, name='home'),
    path('gallery/new/', create_gallery_post, name='gallery-create'),
    path('gallery/<int:post_id>/heart/', toggle_gallery_heart, name='gallery-heart'),
    path('gallery/<int:post_id>/comment/', add_gallery_comment, name='gallery-comment'),
    path('gallery/comment/<int:comment_id>/delete/', delete_gallery_comment, name='gallery-comment-delete'),
    path('gallery/<int:post_id>/delete/', delete_gallery_post, name='gallery-delete'),
    path('trends/', trends_page, name='trends'),
    path('trends/new/', create_trend_article, name='trend-create'),
    path('trends/<slug:slug>/comment/', add_article_comment, name='article-comment-add'),
    path('trends/comment/<int:comment_id>/delete/', delete_article_comment, name='article-comment-delete'),
    path('trends/<slug:slug>/', trend_article_detail, name='trend-article-detail'),
    path('article/minimalist-power-dressing/', full_article_page, name='article-detail'),
    path('insights/', insights_page, name='insights'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('signup/', signup_view, name='signup'),
    path('profile/', profile_view, name='profile'),
]
