# Generated by Django 6.0.2 on 2026-04-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_allow_comments_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
