# Generated by Django 6.0.2 on 2026-04-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_color',
            field=models.CharField(default='#6d28d9', max_length=7),
        ),
    ]
